name: Build Electron App for Windows

on:
  push:
    branches:
      - master   # or 'master', or any other branch you want

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Frontend Dependencies
        working-directory: ./client       
        run: yarn install
  
      - name: Build React Frontend
        working-directory: ./client       
        run: yarn run build
      
      - name: Install Dependencies
        run: yarn install

      - name: Build Windows App
        run: yarn run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
            name: windows-build
            path: dist/*.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
